// AUTO-GENERATED by scripts/inline-wasm.mjs — do not edit by hand.
// Base64 of build/quantvec.wasm (the AssemblyScript scoring kernel, assembly/index.ts).
// Regenerate with `npm run build:wasm`.

/** Base64-encoded quantvec WASM scoring kernel (212 bytes). */
export const WASM_BASE64 =
  'AGFzbQEAAAABDgJgAAF/YAZ/f39/f38AAwQDAQAABQMBAAAHLgQIaGVhcEJhc2UAAQphYmlWZXJzaW9uAAIJc2NvcmVJbnRvAAAGbWVtb3J5AgAKfwNxAgN/AXwDQCABIAdKBEBEAAAAAAAAAAAhCSAAIAIgB2xqIQhBACEGA0AgAiAGSgRAIAkgBCAGIAhqLQAAIAMgBmxqQQJ0aioCALugIQkgBkEBaiEGDAELCyAFIAdBA3RqIAk5AwAgB0EBaiEHDAELCwsGAEGAiAILBABBAgs=';
