// Inline the built WASM kernel as base64 into a committed TS source file, so the
// published bundle (and the test suite) load the kernel with zero config and no
// filesystem/asc dependency at runtime — the key to isomorphic loading.
//
// Run via `npm run build:wasm` (after `asc`): reads build/quantvec.wasm and writes
// src/wasm/wasm-binary.ts. The generated file is committed.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const wasm = readFileSync(join(root, 'build', 'quantvec.wasm'));
const base64 = wasm.toString('base64');

const out = `// AUTO-GENERATED by scripts/inline-wasm.mjs — do not edit by hand.
// Base64 of build/quantvec.wasm (the AssemblyScript scoring kernel, assembly/index.ts).
// Regenerate with \`npm run build:wasm\`.

/** Base64-encoded quantvec WASM scoring kernel (${wasm.length} bytes). */
export const WASM_BASE64 =
  '${base64}';
`;

writeFileSync(join(root, 'src', 'wasm', 'wasm-binary.ts'), out);
process.stdout.write(
  `inlined build/quantvec.wasm (${wasm.length} bytes) → src/wasm/wasm-binary.ts\n`,
);
